version: '3'

services:
  book_api:
    build: ./book_api
    ports:
      - "8081:81"
    networks:
      - appnet

  translate_api:
    build: ./translate_api
    ports:
      - "5000:5000"
    networks:
      - appnet
    depends_on:
      - book_api

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - appnet
  
      

networks:
  appnet:
